<?php
// Set page title.
$this->headTitle($this->translate('BDTD'));

// Disable top search box -- this page has a special layout.
$this->layout()->searchbox = false;

// Set default value if necessary:
if (!isset($this->searchClassId)) {
  $this->searchClassId = 'Solr';
}

$this->layout()->breadcrumbs = false;
$this->layout()->layoutFull = true;
?>

<?php $this->headScript()->appendFile("indicators-home.js"); ?>
<div class="search-box ">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <div class="box-title">
          <h1 class="bdtd-title"><?= $this->transEsc("Biblioteca Digital Brasileira de Teses e Dissertações") ?></h1>
          <h4 class="bdtd-subtitle">Acesso e visibilidade às teses e dissertações brasileiras</h4>
        </div>
      </div>
    </div>
    <div class="indicators text-primary">
      <div class="item">
        <i class="fa fa-university"></i>
        <div class="data">
          <span id="institution" class="main-highlight">000</span>
          <span>Instituições</span>
        </div>
      </div>
      <div class="item"> <i class="fa fa-book"></i>
        <a href="Search/Results?limit=0&lookfor=%2A%3A%2A&type=AllFields&filter%5B%5D=format%3A%22doctoralThesis%22" class="data">
          <span id="doctorThesis" class="main-highlight">000</span>
          <span>Teses</span>
        </a>
      </div>
      <div class="item">
        <i class="fa fa-file-text" aria-hidden="true"></i>
        <a href="Search/Results?limit=0&lookfor=%2A%3A%2A&type=AllFields&filter%5B%5D=format%3A%22masterThesis%22" class="data">
          <span id="masterThesis" class="main-highlight">000</span>
          <span>Dissertações</span>
        </a>
      </div>
      <div class="item">
        <i class="fa fa-file" aria-hidden="true"></i>
        <a href="Search/Results" class="data">
          <span id="total" class="main-highlight">000</span>
          <span>Documentos</span>
        </a>
      </div>
    </div>
    <?php $this->slot('search-home-hero')->start() ?>
    <?= $this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true]) ?>
    <?= $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
    <?= $this->slot('search-home-hero')->end() ?>
  </div>
</div>
<div class="container">
  <div class="search-info bottom-search-form">
    <div class="item">
      <div class="text-primary flex-row-spaced-between">
        <h4 class="main-highlight">
          Participe
        </h4>
        <i class="fa fa-comments" aria-hidden="true"></i>
      </div>
      <p>SAIBA COMO PARTICIPAR DA BIBLIOTECA DIGITAL BRASILEIRA DE TESES E DISSERTAÇÕES (BDTD)</p>
    </div>
    <div class="item">
      <div class="text-primary flex-row-spaced-between">
        <h4 class="main-highlight">
          Tecnologia
        </h4>
        <i class="fa fa-laptop" aria-hidden="true"></i>
      </div>
      <p>A Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) desde a sua criação faz uso de soluções livres em toda a sua estrutura de funcionamento.</p>
    </div>
    <div class="item">
      <div class="text-primary flex-row-spaced-between">
        <h4 class="main-highlight">
          Indicadores
        </h4>
        <i class="fa fa-line-chart" aria-hidden="true"></i>
      </div>
      <p>A Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) desde a sua criação faz uso de soluções livres em toda a sua estrutura de funcionamento.</p>
    </div>
  </div>
</div>
<!-- importa a seção de informações abaixo da busca na página inicial -->
<div class="container">
  <?= $this->render('content-home.phtml') ?>
</div>