<?php
// Set page title.
$this->headTitle($this->translate('BDTD'));

// Disable top search box -- this page has a special layout.
$this->layout()->searchbox = false;

// Set default value if necessary:
if (!isset($this->searchClassId)) {
  $this->searchClassId = 'Solr';
}

$this->layout()->breadcrumbs = false;
?>

<div class="search-box ">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <div class="search-header">
          <h1 class="bdtd-title"><?= $this->transEsc("Biblioteca Digital Brasileira de Teses e Dissertações") ?></h1>
          <h4 class="bdtd-subtitle">Acesso e visibilidade às teses e dissertações brasileiras</h4>
        </div>
      </div>
    </div>
    <div class="indicators text-primary">
      <div class="item">
        <i class="fa fa-university"></i>
        <div class="data">
          <span class="main-highlight">129</span>
          <span>Instituições</span>
        </div>
      </div>
      <div class="item"> <i class="fa fa-book"></i>
        <div class="data">
          <span class="main-highlight">129</span>
          <span>Teses</span>
        </div>
      </div>
      <div class="item">
        <i class="fa fa-file-text" aria-hidden="true"></i>
        <div class="data">
          <span class="main-highlight">129</span>
          <span>Dissertações</span>
        </div>
      </div>
      <div class="item">
        <i class="fa fa-file" aria-hidden="true"></i>
        <div class="data">
          <span class="main-highlight">129</span>
          <span>Documentos</span>
        </div>
      </div>
    </div>
    <?php $this->slot('search-home-hero')->start() ?>
    <?= $this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true]) ?>
    <?= $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
    <?= $this->slot('search-home-hero')->end() ?>
  </div>
</div>
<div class="container">
  <div class="search-info">
    <div class="item">
      <div class="text-primary flex-row-spaced-between">
        <h4 class="main-highlight">
          Participe
        </h4>
        <i class="fa fa-file" aria-hidden="true"></i>
      </div>
      <p>SAIBA COMO PARTICIPAR DA BIBLIOTECA DIGITAL BRASILEIRA DE TESES E DISSERTAÇÕES (BDTD)</p>
    </div>
    <div class="item">
      <div class="text-primary flex-row-spaced-between">
        <h4 class="main-highlight">
          Participe
        </h4>
        <i class="fa fa-file" aria-hidden="true"></i>
      </div>
      <p>SAIBA COMO PARTICIPAR DA BIBLIOTECA DIGITAL BRASILEIRA DE TESES E DISSERTAÇÕES (BDTD)</p>
    </div>
    <div class="item">
      <div class="text-primary flex-row-spaced-between">
        <h4 class="main-highlight">
          Participe
        </h4>
        <i class="fa fa-file" aria-hidden="true"></i>
      </div>
      <p>SAIBA COMO PARTICIPAR DA BIBLIOTECA DIGITAL BRASILEIRA DE TESES E DISSERTAÇÕES (BDTD)</p>
    </div>
  </div>
</div>
<!-- importa a seção de informações abaixo da busca na página inicial -->
<div class="container">
<?= $this->render('content-home.phtml') ?>
</div>