<?php $this->headTitle('TEDE'); ?>
<?php $this->layout()->searchbox = false; ?>
<?php $this->layout()->breadcrumbs .= '<li class="active">' . '' . '</li>'; ?>

<div class="fulltext">
    <h2 class="text-primary">TEDE</h2>
    <br />
    <h3 class="text-secondary">Sistema de Publicação Eletrônica de Teses e Dissertações (TEDE)</h3>
    <br />
    <br />
    <p>
        O Sistema de Publicação Eletrônica de Teses e Dissertações (TEDE) é um software desenvolvido pelo Ibict e distribuído gratuitamente para as instituições que desejam utilizar a solução para o gerenciamento de suas teses e dissertações.
    </p>
    <p>
        A primeira versão do sistema foi lançada em 2002 quando do surgimento da BDTD. A mais recente atualização do TEDE foi lançada em 2014 e que passou a ser chamado, desde então, de TEDE 2. A nova versão é uma customização do software livre DSpace, a mesma solução utilizada para a criação de Repositórios Institucionais de Publicações Científicas em Acesso Aberto.
    </p>
    <p>

        O TEDE2 já está configurado de acordo com o Novo Padrão de Metadados da BDTD, sendo totalmente interoperável com outros sistemas de informação. Ainda, é possível fazer as customizações na interface e definições do fluxo de trabalho dentro do sistema.
    </p>
    <p>
        As instituições que ainda utilizam o antigo TEDE podem migrar diretamente as suas teses e dissertações para o TEDE2. Para isso, o Ibict desenvolveu também uma ferramenta que possibilita a migração das informações, sem a sua perda e sem trabalho duplicado.
    </p>
    <p>
        Tenha acesso ao manual para uso do TEDE 2:
    </p>
    <p>
        <a href="#" target="_blank">
            <span class="glyphicon glyphicon-download fa-2x"> </span> Manual de usuário do TEDE 2
        </a>
    </p>
    <p>

        Acesse também as orientações para instalação e customização do TEDE 2:</p>
    <p>

        <a href="#" target="_blank">
            <span class="glyphicon glyphicon-link "> </span> TEDE / TEDE 2
        </a>
    </p>
    <p>
        <a href="#" target="_blank">
            <span class="glyphicon glyphicon-link "> </span> Instalação, migração e configuração do TEDE 2
        </a>
    </p>
    <p>
        <a href="#" target="_blank">
            <span class="glyphicon glyphicon-link "> </span> Matriz de novas funcionalidades implementadas na customização DSpace/TEDE 2
        </a>
    </p>
    <p>
        <a href="#" target="_blank">
            <span class="glyphicon glyphicon-link "> </span> Manual de usuário do TEDE 2
        </a>
    </p>
    <p>
        <a href="#" target="_blank">
            <span class="glyphicon glyphicon-link "> </span> Configurações básicas / avançadas
        </a>
    </p>
    <p>
        <a href="#" target="_blank">
            <span class="glyphicon glyphicon-link "> </span> Problema / solução (Troubleshooting) - TEDE 2
        </a>

    </p>
</div>