<?php $this->headTitle('Tecnologia'); ?>
<?php $this->layout()->searchbox = false; ?>
<?php $this->layout()->breadcrumbs .= '<li class="active">' . '' . '</li>'; ?>

<div class="fulltext">
    <h2 class="text-primary">Tecnologia</h2>
    <br />
    <h3 class="text-secondary">
        Conheça as principais tecnologias utilizadas na BDTD
    </h3>
    <br />
    <p>
        Considerando que o foco primordial da Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) é disseminar e facilitar o acesso livre de custos à pesquisa realizada no território nacional, a plataforma adota exclusivamente soluções tecnológicas de código aberto para seu funcionamento. Atualmente, dois softwares desempenham papéis fundamentais nesse processo: o coletador, um software desenvolvido pela plataforma <a href="https://github.com/lareferencia" target="_blank" rel="noopener noreferrer">LA Referencia</a>, encarregado de reunir os dados provenientes das fontes de coleta da BDTD, e o <a href="https://vufind.org" target="_blank" rel="noopener noreferrer">VuFind</a>, uma interface web que permite aos usuários visualizar, de forma agregada, todas as informações coletadas pelo sistema.
    </p>
</div>