<?php $this->headScript()->appendFile("indicators-home.js"); ?>

<div class="about">
    <h2 class="main-second-title title-primary">BDTD</h2>
    <p>
        O IBICT desenvolveu e coordena a Biblioteca Digital Brasileira de Teses e Dissertações (BDTD), que integra os sistemas de informação de teses e dissertações existentes nas instituições de ensino e pesquisa do Brasil, e também estimula o registro e a publicação de teses e dissertações eletrônico. A BDTD, em parceria com as instituições brasileiras de ensino e pesquisa, possibilita que a comunidade brasileira de C&T publique e difunda suas teses e dissertações produzidas no País e no exterior, dando maior visibilidade à produção científica nacional.
    </p>
</div>

<div class="partners">
    <a class="partner oasisbr" href="https://oasisbr.ibict.br/vufind/" target="_blank">
        <div class="partner-logo">
            <img src="<?= $this->imageLink('partners/oasisbr.png'); ?>" alt="logo do oasisbr">
        </div>
        <div class="partner-desc">
            <h3 class="main-highlight">Oasisbr</h3>
            <p>Portal brasileiro de publicações e dados científicos em acesso aberto</p>
        </div>
    </a>
    <a class="partner deposita" href="https://deposita.ibict.br/" target="_blank">
        <div class="partner-logo">
            <img src="<?= $this->imageLink('partners/deposita.png'); ?>" alt="logo do deposita">
        </div>
        <div class="partner-desc">
            <h3 class="main-highlight">Deposita</h3>
            <p>Repositório Comum do Brasil</p>
        </div>
    </a>
    <a class="partner lareferencia" href="https://www.lareferencia.info/pt/" target="_blank">
        <div class="partner-logo">
            <img src="<?= $this->imageLink('partners/la_referencia.png'); ?>" alt="logo da la-refencia">
        </div>
        <div class="partner-desc">
            <h3 class="main-highlight">LA Referencia</h3>
            <p>Red de repositorios de acceso abierto a la ciencia</p>
        </div>
    </a>
    <a class="partner ndltd" href="https://ndltd.org/" target="_blank">
        <div class="partner-logo">
            <img src="<?= $this->imageLink('partners/ndltd.png'); ?>" alt="logo da ndltd">
        </div>
        <div class="partner-desc">
            <h3 class="main-highlight">NDLTD</h3>
            <p>The Networked Digital Library of Theses and Dissertations</p>
        </div>
    </a>
</div>