<footer class="hidden-print">
  <div class="container-fluid social-media">
    <div class="flex-row-center gap-2">
      <a href="https://www.youtube.com/user/IBICTbr/" target="_blank">
        <img class="img-responsive" src="<?= $this->imageLink('youtube.png'); ?>" alt="Youtube Logo" />
      </a>
      <a href="https://www.facebook.com/IBICTbr/" target="_blank">
        <img class="img-responsive" src="<?= $this->imageLink('facebook.png'); ?>" alt="Facebook Logo" />
      </a>
      <a href="https://twitter.com/ibictbr" target="_blank">
        <img class="img-responsive" src="<?= $this->imageLink('twitter.png'); ?>" alt="Twitter Logo" />
      </a>
      <a href="https://www.linkedin.com/company/ibict---instituto-brasileiro-de-informa-o-em-ci-ncia-e-tecnologia/mycompany/" target="_blank">
        <img class="img-responsive" src="<?= $this->imageLink('linkedin.svg'); ?>" alt="Linkedin Logo" />
      </a>
    </div>
  </div>
  <div class="assinatura">
    <a href="https://www.gov.br/ibict" target="_blank" rel="noopener noreferrer">
      <img class="img-responsive" src="<?= $this->imageLink('assinatura.png'); ?>" alt="Logo do Ibict e do ministério da ciência e tecnologia" />
    </a>
  </div>
  <p>
    Instituto Brasileiro de Informação em Ciência e Tecnologia (Ibict) <br />
    SAUS Quadra 5 - Lote 6 Bloco H - Asa sul - CEP: 70.070-912 - Brasília - DF
  </p>
  <div class="poweredby">
    <?= $this->layout()->poweredBy ?>
  </div>
  <script async src="https://barra.brasil.gov.br/barra_2.0.js"></script>
</footer>