<footer class="hidden-print">
  <div class="assinatura">
    <img class="img-responsive" src="<?= $this->imageLink('assinatura.png'); ?>" alt="Logo do IBICT e do ministério da ciência e tecnologia" />
    <img class="img-responsive" src="<?= $this->imageLink('gov.png'); ?>" alt="Logo do governo federal" />
  </div>
  <p>
  Instituto Brasileiro de Informação em Ciência e Tecnologia (Ibict) <br/>
  SAUS Quadra 5 - Lote 6 Bloco H - Asa sul - CEP: 70.070-912 - Brasília - DF
  </p>
  <div class="poweredby">
    <?= $this->layout()->poweredBy ?>
  </div>
  <script async src="https://barra.brasil.gov.br/barra_2.0.js"></script>
</footer>