<?php $this->headTitle($this->translate('Perguntas Frequentes')); ?>
<?php $this->layout()->searchbox = false; ?>
<?php $this->layout()->breadcrumbs .= '<li class="active">' . '' . '</li>'; ?>

<div class="fulltext">
  <h1 class="text-primary">FAQ</h1>
  <br />
  <h2 class="text-secondary">Dúvidas frequentes</h2>
  <br /> <br />
  <div class="faq">
    <div class="row ">
      <div class="col-md-12">
        <div class="card">
          <h3> <a data-toggle="collapse" class="btn-collapse collapsed" href="#1" aria-expanded="false" aria-controls="footwear">
              <?= $this->transEsc('O que é a Biblioteca Digital Brasileira de Teses e Dissertações (BDTD)?'); ?></a>
          </h3>
          <div class="collapse" id="1">
            <p>
              A Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) integra e dissemina, em um só portal de busca, os textos completos das teses e dissertações defendidas nas instituições brasileiras de ensino e pesquisa. O acesso a essa produção científica é livre de quaisquer custos. Além disso, a BDTD também coleta as teses e dissertações defendidas por brasileiros em instituições de ensino estrangeiras.</p>
            <p>
              A BDTD contribui para o aumento de conteúdos de teses e dissertações brasileiras na internet, o que significa a maior visibilidade da produção científica nacional e a difusão de informações de interesse científico e tecnológico para a sociedade em geral.Ademais, a BDTD também proporciona maior visibilidade e governança do investimento realizado em programas de pós-graduação.
            </p>
          </div>
        </div>
        <div class="card">
          <h3> <a data-toggle="collapse" class="btn-collapse collapsed" href="#2" aria-expanded="false" aria-controls="footwear">
              <?= $this->transEsc('O que devo fazer para que minha tese e/ou dissertação seja coletada pela BDTD?'); ?></a>
          </h3>
          <div class="collapse" id="2">
            <p>
              Para que seu documento possa ser coletado pela BDTD é essencial que ele esteja disponível em umas das fontes de informação científica coletadas pelo Portal. Consulte no menu dentro da aba de Redes as <a href="../datasources">instituições participantes</a> para verificar se a fonte de informação em que seu documento foi publicado já faz parte da BDTD.</p>

            <p>Caso a fonte de informação em que se encontra o seu documento ainda não seja coletada pela BDTD, sugerimos que, inicialmente, entre em contato com o gestor da instituição para que ele possa acionar a equipe da BDTD. Caso a sua instituição de defesa não tenha uma Biblioteca local de teses e dissertações ou um Repositório Digital orientamos que faça o auto depósito de seu trabalho no <a href="https://deposita.ibict.br/" target="_blank" rel="noopener noreferrer">Repositório Comum do Brasil (Deposita)</a>, o qual é coletado pela BDTD.</p>

            <p>Para aqueles que obtiveram o grau de mestre ou doutor em instituição estrangeira, a orientação é que faça o auto depósito de seu trabalho no Deposita.
            </p>
          </div>
        </div>
        <div class="card">
          <h3> <a data-toggle="collapse" class="btn-collapse collapsed" href="#3" aria-expanded="false" aria-controls="footwear">
              <?= $this->transEsc('Quais os procedimentos para que a minha instituição passe a integrar a BDTD?'); ?></a>
          </h3>
          <div class="collapse" id="3">
            <p>
              Para integração da sua instituição à BDTD necessitamos que nos encaminhe um Ofício para formalizar a solicitação, informando previamente o nome do responsável da Biblioteca (ou do responsável pelo gerenciamento informacional do sistema que disponibiliza teses e dissertações da instituição, caso essa gestão seja feita separadamente), e-mail, telefone para contato, nome, sigla e endereço da Instituição e breve informação sobre o(s) curso(s) de pós-graduação stricto sensu.</p>

            <p>Após recebimento do documento, a Equipe BDTD entrará em contato com o(a) responsável indicado(a) para o seguimento do processo de integração à BDTD.</p>

            <p>Contate-nos pelo email: <b>equipebdtd@ibict.br</b></p>

            <p>Link para o modelo de ofício.</p>
          </div>
        </div>
        <div class="card">
          <h3> <a data-toggle="collapse" class="btn-collapse collapsed" href="#4" aria-expanded="false" aria-controls="footwear">
              <?= $this->transEsc('Quais as vantagens da minha instituição integrar a BDTD?'); ?></a>
          </h3>
          <div class="collapse" id="4">
            <p>
              Sendo coletada pela BDTD, a instituição por meio de sua biblioteca digital passa a contribuir para o aumento da visibilidade dos conteúdos compartilhados. Sendo a BDTD uma referência de infraestrutura informacional e interoperabilidade de dados a produção científica informacional ganha projeção, também, no cenário internacional por meio de acordos de compartilhamento de dados entre a BDTD e a <a href="https://ndltd.org/" target="_blank" rel="noopener noreferrer">Networked Digital Library of Theses and Dissertations (NDLTD)</a>, que é uma organização dedicada a promover a disseminação, preservação e uso das teses e dissertações eletrônicas.
            </p>
          </div>
        </div>
        <div class="card">
          <h3> <a data-toggle="collapse" class="btn-collapse collapsed" href="#5" aria-expanded="false" aria-controls="footwear">
              <?= $this->transEsc('Não encontrei minha tese e/ou dissertação na BDTD, como devo proceder?'); ?></a>
          </h3>
          <div class="collapse" id="5">
            <p>
              A BDTD coleta as informações sobre as teses e dissertações disponibilizadas nos sistemas de informação das instituições que participam da Rede.</p>

            <p>O primeiro passo é contactar a instituição em que foi submetido o trabalho para averiguar se consta na Biblioteca Digital da própria instituição. Em caso positivo, o sistema de coleta disponibilizará o trabalho no catálogo da BDTD. Em casos especiais o autor ou instituição pode entrar em contato com o suporte para certificarmos se existe alguma incompatibilidade no sistema de interoperabilidade.
            </p>
          </div>
        </div>
        <div class="card">
          <h3> <a data-toggle="collapse" class="btn-collapse collapsed" href="#6" aria-expanded="false" aria-controls="footwear">
              <?= $this->transEsc('A coleta de dados da minha instituição não está atualizada, o que fazer?'); ?></a>
          </h3>
          <div class="collapse" id="6">
            <p>
              O primeiro passo é verificar a quantidade total de documentos depositados na interface de usuário. Ao fazer uma busca em branco é possível verificar quantos documentos estão depositados na base. Após isso, verifique se o quantitativo de documentos indexados na interface OAI do repositório é o mesmo da interface de usuário. Em caso negativo, solicite ao responsável técnico de sua instituição que faça a atualização da interface OAI. Em caso positivo, entre em contato com a equipe BDTD para verificarmos outras possibilidades.
            </p>
          </div>
        </div>
        <br />
        <p><b>Não encontrou o que procurava?</b></p>
        <p>Entre em contato com a nossa equipe e faremos o possível para te ajudar.</p>
        <a class="btn contained-primary fit-content" href="mailto:equipebdtd@ibict.br">Suporte</a>
      </div>
    </div>
  </div>
</div>