<?php $this->headTitle('Como participar'); ?>
<?php $this->layout()->searchbox = false; ?>
<?php $this->layout()->breadcrumbs .= '<li class="active">' . '' . '</li>'; ?>

<div class="fulltext">
    <h2 class="text-primary">Como participar?</h2>
    <br />
    <h3 class="text-secondary">
        SAIBA COMO PARTICIPAR DA BIBLIOTECA DIGITAL BRASILEIRA DE TESES E DISSERTAÇÕES (BDTD)
    </h3>
    <br />
    <br />
    <p>
        Para participar da Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) é necessário que a instituição possua curso(s) de pós-graduação stricto sensu. Para o processo de integração da instituição à BDTD é necessário o encaminhamento de uma comunicação formal manifestando o interesse em fazer parte da BDTD.
    </p>
    <p>
        Após recebimento do documento, a Equipe da BDTD entrará em contato com o responsável indicado para o seguimento do processo de integração à BDTD.
    </p>
</div>